#!/usr/bin/env python3
"""Emit a pip --require-hashes lockfile from the wheels in a directory.

Usage: _gen_lock.py <wheelhouse_dir>   (prints the lockfile to stdout)

One wheel per package is expected (single-platform download). Wheel filenames are
`name-version-pytag-abitag-platform.whl`; name/version are the first two `-` fields.
"""
import hashlib
import os
import re
import sys


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def norm(name):
    return re.sub(r"[-_.]+", "-", name).lower()


def main():
    wheelhouse = sys.argv[1]
    entries = []
    for fn in sorted(os.listdir(wheelhouse)):
        if not fn.endswith(".whl"):
            continue
        parts = fn.split("-")
        name, version = parts[0], parts[1]
        entries.append((norm(name), version, sha256(os.path.join(wheelhouse, fn))))

    seen = {}
    for name, version, _ in entries:
        seen.setdefault(name, set()).add(version)
    dupes = {n: v for n, v in seen.items() if len(v) > 1}
    if dupes:
        sys.exit(f"ERROR: multiple versions for {dupes} -- wheelhouse not single-platform")

    print("# Generated by scripts/build-wheelhouse.sh -- do not edit by hand.")
    print("# Hash-pinned for `pip install --require-hashes --no-index`.")
    for name, version, digest in entries:
        print(f"{name}=={version} \\")
        print(f"    --hash=sha256:{digest}")


if __name__ == "__main__":
    main()
